### ISSUE TITLE
api请求存在返回问题

### ISSUE THREAD

**Issue by XdpCs** [sinsoio/sinso-getway-demo#8]
File List
Intro
List of user uploaded files
HTTP Requests
Method: GET
Url: /v1/files
返回1003 参数错误

**Comment by sumkey** [comment]
Make sure to check the request parameters, current and size are required

**Comment by XdpCs** [comment]
if i want to get file ，what should i do?

**Comment by XdpCs** [comment]
your website don't have a suitable api.

**Comment by sumkey** [comment]
The official view can be reached, https://docs.getway.sinso.io/docs/api
